### ISSUE TITLE
Add API to open user profile programmatically

### ISSUE THREAD

**Issue by wladikpasika** [FastComments/fastcomments-react#65] opened 2023-09-03 12:53 UTC
**Is your feature request related to a problem? Please describe.**
We couldn't figure out how to open a user profile programmatically. For instance by clicking on a button outside the Iframe.

**Describe the solution you'd like**
Implement API, that can solve the issue - maybe some callback or item that we can add to the react component.

**Additional context**
![Screenshot 2023-09-03 at 15 40 20](https://github.com/FastComments/fastcomments-react/assets/30317614/57015334-466a-43c0-bfc5-5f1f993ed4b5)
![Screenshot 2023-09-03 at 15 43 13](https://github.com/FastComments/fastcomments-react/assets/30317614/2dd418a3-5ca8-4799-9ffd-7f8eaac1a83b)

**Comment by winrid** [comment] 2023-09-03 15:53
@wladikpasika Yeah, there is no way today. Will take a look.

**Comment by winrid** [comment] 2023-09-03 21:39
@wladikpasika I've added an example in master: https://github.com/FastComments/fastcomments-react/commit/4ee4c47ff869bc86bb3081cc4ea46ad07eae4140#diff-5149ca27915951c718099311594f43508ce00a3e6dad9cfcc58a2c1faebcfa1dR17

But there are some bugs. Will have a follow update and new version soon.

**Comment by wladikpasika** [comment] 2023-09-04 11:53
@winrid Thanks for the example!

**Comment by winrid** [comment] 2023-09-05 08:19
@wladikpasika `3.1.0` now has a functional example of this ask. Verified works as intended. Closing.

**Closed by winrid** 2023-09-05 08:19 UTC
